name: 01.changelog

on:
  workflow_dispatch:

jobs:
  build: # make sure we can build action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: conventional-commits-changelog
        id: ch
        uses: workflow-actions/conventional-changelog-action@main
        with:
          name: run-action

      - name: output
        run: echo ${{steps.ch.outputs.changelog}}